/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.valkey.javabenchmark;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.InputStream;
import java.util.Properties;

/**
 * Provides build-time information such as git commit ID.
 * 
 * <p>This class reads from git.properties file generated by the
 * git-commit-id-maven-plugin during the build process.</p>
 *
 * @author Ilia Kolominsky
 */
public final class BuildInfo {
    
    private static final Logger logger = LoggerFactory.getLogger(BuildInfo.class);
    private static final String GIT_PROPERTIES_PATH = "/git.properties";
    
    private static final Properties gitProperties = new Properties();
    private static boolean loaded = false;
    
    static {
        loadGitProperties();
    }
    
    private BuildInfo() {
        // Utility class
    }
    
    private static void loadGitProperties() {
        try (InputStream is = BuildInfo.class.getResourceAsStream(GIT_PROPERTIES_PATH)) {
            if (is != null) {
                gitProperties.load(is);
                loaded = true;
                logger.debug("Loaded git.properties: commit={}", getCommitIdShort());
            } else {
                logger.debug("git.properties not found (expected during development)");
            }
        } catch (Exception e) {
            logger.warn("Failed to load git.properties: {}", e.getMessage());
        }
    }
    
    /**
     * Check if git properties were successfully loaded.
     * 
     * @return true if git.properties was found and loaded
     */
    public static boolean isAvailable() {
        return loaded;
    }
    
    /**
     * Get the full git commit ID (40-character SHA).
     * 
     * @return the full commit ID, or null if not available
     */
    public static String getCommitIdFull() {
        return gitProperties.getProperty("git.commit.id.full");
    }
    
    /**
     * Get the short git commit ID (typically 7 characters).
     * 
     * @return the short commit ID, or null if not available
     */
    public static String getCommitIdShort() {
        String shortId = gitProperties.getProperty("git.commit.id.abbrev");
        if (shortId != null) {
            return shortId;
        }
        // Fallback to truncating full ID
        String fullId = getCommitIdFull();
        return fullId != null && fullId.length() >= 7 ? fullId.substring(0, 7) : fullId;
    }
    
    /**
     * Get the git branch name.
     * 
     * @return the branch name, or null if not available
     */
    public static String getBranch() {
        return gitProperties.getProperty("git.branch");
    }
    
    /**
     * Check if the git working directory was dirty (had uncommitted changes) at build time.
     * 
     * @return true if dirty, false if clean, null if unknown
     */
    public static Boolean isDirty() {
        String dirty = gitProperties.getProperty("git.dirty");
        return dirty != null ? Boolean.parseBoolean(dirty) : null;
    }
    
    /**
     * Get the git commit timestamp.
     * 
     * @return the commit timestamp, or null if not available
     */
    public static String getCommitTime() {
        return gitProperties.getProperty("git.commit.time");
    }
    
    /**
     * Get the build timestamp.
     * 
     * @return the build timestamp, or null if not available
     */
    public static String getBuildTime() {
        return gitProperties.getProperty("git.build.time");
    }
    
    /**
     * Get a summary string suitable for metadata (short commit ID with dirty indicator).
     * 
     * @return summary like "abc1234" or "abc1234-dirty", or null if not available
     */
    public static String getCommitSummary() {
        String shortId = getCommitIdShort();
        if (shortId == null) {
            return null;
        }
        
        Boolean dirty = isDirty();
        if (Boolean.TRUE.equals(dirty)) {
            return shortId + "-dirty";
        }
        return shortId;
    }
}
